// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WoG2D4XmWCcpQvw2P812RR8IGkIlAtM',
    appId: '1:239961648303:web:2b1d10c2fa2b15728e385a',
    messagingSenderId: '239961648303',
    projectId: 'reddit-2aa16',
    authDomain: 'reddit-2aa16.firebaseapp.com',
    storageBucket: 'reddit-2aa16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKUHx33bs-MvyTvsj51Y0jYRsBU4qSNBM',
    appId: '1:239961648303:android:3d7ef47f543613708e385a',
    messagingSenderId: '239961648303',
    projectId: 'reddit-2aa16',
    storageBucket: 'reddit-2aa16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDot6C2CReAuJj8sr5WjvJZjUDMHuf9a9A',
    appId: '1:239961648303:ios:28988c4030504ba48e385a',
    messagingSenderId: '239961648303',
    projectId: 'reddit-2aa16',
    storageBucket: 'reddit-2aa16.appspot.com',
    iosClientId:
        '239961648303-inqaobbhmb16n3qema2ka06026rgr57i.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
